# SPDX-License-Identifier: Apache-2.0
# Copyright (c) 2025 FlyDSL Project Contributors

"""Ordinary MoE facades for the shared MXFP4/FP8 kernel builders."""

import functools

from aiter.ops.flydsl.moe_common import GateMode

# a16w4 (bf16 A x mxfp4 W) SiTUv2 is now served by the ported FlyDSL kernel
# (aiter/ops/flydsl/kernels/moe_2stage_a16wmix), built via compile_flydsl_moe_stage{1,2}
# and launched by flydsl_a16w4_gemm{1,2} from the a16w4 branches of
# _flydsl_moe_stage{1,2}_impl (aiter/ops/flydsl/moe_kernels.py); its old builders were
# removed from mixed_moe_gemm_2stage_common. The a8w4/mxfp8/a4w4 builders are unchanged.
from .mixed_moe_gemm_2stage_common import (
    compile_mixed_moe_gemm1_common,
    compile_mixed_moe_gemm2_common,
    validate_moe_dtypes,
)

__all__ = [
    "GateMode",
    "compile_mixed_moe_gemm1",
    "compile_mixed_moe_gemm2",
    "validate_moe_dtypes",
]


@functools.cache
def compile_mixed_moe_gemm1(
    *,
    model_dim: int,
    inter_dim: int,
    experts: int,
    topk: int,
    tile_m: int,
    tile_n: int,
    tile_k: int,
    doweight_stage1: bool,
    a_dtype: str = "fp8",
    b_dtype: str = "fp4",
    out_dtype: str = "f16",
    act: str = "silu",
    use_cshuffle_epilog: bool | None = None,
    enable_bias: bool = False,
    model_dim_pad: int = 0,
    inter_dim_pad: int = 0,
    persist_m: int = 1,
    use_async_copy: bool = False,
    waves_per_eu: int = 4,
    k_batch: int = 1,
    b_nt: int = 0,
    gate_mode: GateMode = GateMode.SEPARATED,
    a_scale_one: bool = False,
    xcd_swizzle: int = 0,
    k_wave: int = 1,
    block_waves: int | None = None,
    v2_output_layout: bool = False,
    a_source_bf16: bool = False,
    bf16_load_ahead: bool = False,
    mask_padded_a: bool = False,
    sort_block_m: int = 0,
    kimi_shared_bf16: bool = False,
    kimi_shared_weight_layout: str = "preshuffled",
    kimi_shared_b_cache_mod: int | None = None,
    kimi_shared_wave_local_wait: bool = False,
    kimi_shared_pipeline_wait: str = "default",
    kimi_shared_start_sleep: int = 0,
    kimi_routed_late_a1: bool = False,
    kimi_routed_a_ring2: bool = False,
    kimi_routed_b_ring4: bool = False,
    kimi_routed_b_early4: bool = False,
    kimi_routed_b_half_carry: bool = False,
    kimi_routed_priority3: bool = False,
    kimi_shared_wg_schedule: str = "prefix",
    kimi_shared_grid_split_k: int = 1,
    kimi_shared_grid_tile_n: int = 32,
    kimi_shared_grid_n_major: bool = False,
    kimi_shared_fused_reduce: bool = False,
    kimi_shared_identity_m_indices: bool = False,
    kimi_shared_a_lds_swizzle: bool = False,
    kimi_shared_vec2_partials: bool = False,
):
    """Compile an ordinary stage1 MoE kernel."""
    return compile_mixed_moe_gemm1_common(
        model_dim=model_dim,
        inter_dim=inter_dim,
        experts=experts,
        topk=topk,
        tile_m=tile_m,
        tile_n=tile_n,
        tile_k=tile_k,
        doweight_stage1=doweight_stage1,
        a_dtype=a_dtype,
        b_dtype=b_dtype,
        out_dtype=out_dtype,
        act=act,
        use_cshuffle_epilog=use_cshuffle_epilog,
        enable_bias=enable_bias,
        model_dim_pad=model_dim_pad,
        inter_dim_pad=inter_dim_pad,
        persist_m=persist_m,
        use_async_copy=use_async_copy,
        waves_per_eu=waves_per_eu,
        k_batch=k_batch,
        b_nt=b_nt,
        gate_mode=gate_mode,
        a_scale_one=a_scale_one,
        xcd_swizzle=xcd_swizzle,
        k_wave=k_wave,
        block_waves=block_waves,
        v2_output_layout=v2_output_layout,
        a_source_bf16=a_source_bf16,
        bf16_load_ahead=bf16_load_ahead,
        mask_padded_a=mask_padded_a,
        sort_block_m=sort_block_m,
        kimi_shared_bf16=kimi_shared_bf16,
        kimi_shared_weight_layout=kimi_shared_weight_layout,
        kimi_shared_b_cache_mod=kimi_shared_b_cache_mod,
        kimi_shared_wave_local_wait=kimi_shared_wave_local_wait,
        kimi_shared_pipeline_wait=kimi_shared_pipeline_wait,
        kimi_shared_start_sleep=kimi_shared_start_sleep,
        kimi_routed_late_a1=kimi_routed_late_a1,
        kimi_routed_a_ring2=kimi_routed_a_ring2,
        kimi_routed_b_ring4=kimi_routed_b_ring4,
        kimi_routed_b_early4=kimi_routed_b_early4,
        kimi_routed_b_half_carry=kimi_routed_b_half_carry,
        kimi_routed_priority3=kimi_routed_priority3,
        kimi_shared_wg_schedule=kimi_shared_wg_schedule,
        kimi_shared_grid_split_k=kimi_shared_grid_split_k,
        kimi_shared_grid_tile_n=kimi_shared_grid_tile_n,
        kimi_shared_grid_n_major=kimi_shared_grid_n_major,
        kimi_shared_fused_reduce=kimi_shared_fused_reduce,
        kimi_shared_identity_m_indices=kimi_shared_identity_m_indices,
        kimi_shared_a_lds_swizzle=kimi_shared_a_lds_swizzle,
        kimi_shared_vec2_partials=kimi_shared_vec2_partials,
    )


@functools.cache
def compile_mixed_moe_gemm2(
    *,
    model_dim: int,
    inter_dim: int,
    experts: int,
    topk: int,
    tile_m: int,
    tile_n: int,
    tile_k: int,
    doweight_stage2: bool,
    a_dtype: str = "fp8",
    b_dtype: str = "fp4",
    out_dtype: str = "f16",
    use_cshuffle_epilog: bool | None = None,
    accumulate: bool = True,
    enable_bias: bool = False,
    model_dim_pad: int = 0,
    inter_dim_pad: int = 0,
    persist_m: int = 4,
    sort_block_m: int = 0,
    waves_per_eu: int | None = None,
    use_async_copy: bool = False,
    cu_num_mul: int = 1,
    b_nt: int = 0,
    xcd_swizzle: int = 0,
):
    """Compile an ordinary stage2 MoE kernel."""
    return compile_mixed_moe_gemm2_common(
        model_dim=model_dim,
        inter_dim=inter_dim,
        experts=experts,
        topk=topk,
        tile_m=tile_m,
        tile_n=tile_n,
        tile_k=tile_k,
        doweight_stage2=doweight_stage2,
        a_dtype=a_dtype,
        b_dtype=b_dtype,
        out_dtype=out_dtype,
        use_cshuffle_epilog=use_cshuffle_epilog,
        accumulate=accumulate,
        enable_bias=enable_bias,
        model_dim_pad=model_dim_pad,
        inter_dim_pad=inter_dim_pad,
        persist_m=persist_m,
        sort_block_m=sort_block_m,
        waves_per_eu=waves_per_eu,
        use_async_copy=use_async_copy,
        cu_num_mul=cu_num_mul,
        b_nt=b_nt,
        xcd_swizzle=xcd_swizzle,
    )
